sudo: false
language: scala
jdk:
  - oraclejdk8
env:
  global:
    - GIT_AUTHOR_NAME="Travis CI"
    - GIT_COMMITTER_NAME="Travis CI"
branches:
  only:
    - master
script:
  - ./gradlew check build
# after_success:
#   - ./gradlew reportScoverage coveralls publishGhPages
