#!/bin/bash

SCRIPT_PATH=$(dirname $0)

if [ -z "$1" ] ; then
	echo 'usage: cassandra <command>'
	exit 2
fi

case "$1" in
recreate)
	$SCRIPT_PATH/recreate-tables-cassandra.py
	;;
*)
	echo Unrecognized command \'$1\'
	exit 1
	;;
esac
