#!/bin/bash

SCRIPT_PATH=$(dirname $0)

if [ -z "$1" ] ; then
	echo 'usage: cassandra <command>'
	exit 2
fi

SCRIPT_NAME=$1-tables-dynamo.sh
SCRIPT=$SCRIPT_PATH/$SCRIPT_NAME

if [ -x $SCRIPT ] ; then
	$SCRIPT
	exit 0
else
	echo Unrecognized command \'$1\'
	exit 1
fi
